- name: Install system dependencies
  become: yes
  apt:
    name: ["apt-transport-https", "ca-certificates", "curl", "software-properties-common", "gnupg"]
  tags:
    - docker

- name: Add Docker GPG key
  become: yes
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  tags:
    - docker

- name: Add Docker apt repository
  become: yes
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu {{ ansible_distribution_release | lower }} stable"
    state: present
  tags:
    - docker

- name: Install Docker
  become: yes
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
  tags:
    - docker

- name: Create Docker plugin directory
  file:
    path: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins"
    state: directory
  tags:
    - docker

- name: Install Docker Compose V2
  get_url:
    url: https://github.com/docker/compose/releases/download/v2.0.1/docker-compose-linux-x86_64
    dest: "{{ lookup('env', 'HOME') }}/.docker/cli-plugins/docker-compose"
    mode: "+x"
  tags:
    - docker
