- name: Add Github GPG Key
  become: yes
  shell: "curl -fsSL https://cli.github.com/packages/githubcli-archive-keyring.gpg | dd of=/usr/share/keyrings/githubcli-archive-keyring.gpg"
  tags:
    - install
    - gh
    - dotfiles

# This only work for Debian based distibutions
- name: Get DEB architecture
  shell: dpkg --print-architecture
  register: deb_architecture
  tags:
    - install
    - gh
    - dotfiles

- name: Add Github apt repository
  become: yes
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/githubcli-archive-keyring.gpg] https://cli.github.com/packages stable main"
  tags:
    - install
    - gh
    - dotfiles

- name: Install Github CLI
  become: yes
  apt:
    name: gh
  tags:
    - install
    - gh
    - dotfiles
