- name: Add Neovim PPA
  become: yes
  ansible.builtin.apt_repository:
    repo: ppa:neovim-ppa/stable
  tags:
    - install
    - neovim

- name: Install neovim
  become: yes
  apt:
    name: 'neovim'
  tags:
    - install
    - neovim
