- name: Install Node Version Manager
  shell: >
    curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
  args:
    creates: "{{ lookup('env', 'HOME') }}/.nvm/nvm.sh"
  tags:
    - install
    - node

- name: Install lts version of Node
  shell: "source {{ lookup('env', 'HOME') }}/.nvm/nvm.sh && nvm install --lts"
  args:
    executable: /bin/bash
  tags:
    - install
    - node
