- name: Get Starship installer
  get_url:
    url: https://starship.rs/install.sh
    dest: /tmp/starship_install.sh
    mode: '+x'
  tags:
    - install
    - starship

- name: Install Starship
  become: yes
  shell:
    cmd: /tmp/starship_install.sh --yes
    executable: '/bin/sh'
  tags:
    - install
    - starship
