---
- name: Add HashiCorp GPG key
  become: true
  apt_key:
    url: https://apt.releases.hashicorp.com/gpg
    state: present

- name: Add HashiCorp repository
  become: true
  apt_repository:
    repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release | lower }} main"
    state: present

- name: Install vagrant
  become: true
  ansible.builtin.package:
    name: vagrant
    state: latest

