---
- name: Install core packages
  become: true
  apt:
    name:
      - build-essential
      - software-properties-common
      - unzip
      - apt-utils
      - curl
      - lsof
      - moreutils
      - direnv
      - fzf
      - jq
      - tree
      - gnupg
      - apt-transport-https
      - ca-certificates
      - xclip
      - xsel
      - libnss3-tools
    state: latest
